#!/bin/sh

### BEGIN INIT INFO
# Provides:	     siem9daemon
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: siem9
# Description:       siem9 start-stop-daemon - Debian
### END INIT INFO

NAME="siem9"
APPDIR="/root/siem9/"
APPBIN="/usr/bin/python"
APPARGS="client.py $(who | awk '{print $1}')" #hack
USER="root"
GROUP="root"

start() {
    printf "Starting '$NAME'... "
    start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/$NAME.pid --chdir "$APPDIR" --exec "$APPBIN" -- $APPARGS || true
    printf "done\n"
}

killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
	killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
    printf "Stopping '$NAME'... "
    [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
    while test -d /proc/$(cat /var/run/$NAME.pid); do
	killtree $(cat /var/run/$NAME.pid) 15
	sleep 0.5
    done 
    [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
    printf "done\n"
}

case "$1" in
    'start')
	start
        touch /var/lock/subsys/siem9
        ;;
    'stop')
	stop
        rm -f /var/lock/subsys/siem9
        ;;
    *)
	echo "usage: service siem9 start|stop"
	;;
esac
