# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clientinfo_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bash_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('command', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
