# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20161130_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bash_History',
        ),
    ]
